In [2]:
## 7.2
import numpy as np

In [4]:
numbers = np.array([3,5,6,4,7])

In [5]:
numbers

array([3, 5, 6, 4, 7])

In [6]:
type(numbers)

numpy.ndarray

In [11]:
list = [item for item in range(1,20,2)]
np.array(list)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [12]:
## 7.3
integers = np.array([[1,2,3],[4,5,6]])

In [13]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
floats = np.array([0.0,0.1,0.2,0.3,0.4])

In [15]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [17]:
integers.dtype

dtype('int32')

In [19]:
floats.dtype

dtype('float64')

In [20]:
integers.ndim

2

In [21]:
floats.ndim

1

In [22]:
integers.shape

(2, 3)

In [23]:
floats.shape

(5,)

In [24]:
integers.size

6

In [25]:
floats.size

5

In [26]:
floats.itemsize

8

In [27]:
integers.itemsize

4

In [30]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [31]:
for i in integers.flat:
    print(i, end= ' ')

1 2 3 4 5 6 

In [32]:
sc7_3 = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [37]:
sc7_3.ndim

2

In [36]:
sc7_3.shape

(2, 5)

In [40]:
## 7.4
zero = np.zeros(6)

In [41]:
zero.dtype

dtype('float64')

In [42]:
np.ones(3)

array([1., 1., 1.])

In [44]:
np.ones((2,4), dtype=int).dtype

dtype('int32')

In [47]:
np.full((3,5),12,dtype=int)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [49]:
## 7.5
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(5,8)

array([5, 6, 7])

In [52]:
np.arange(40,1,-3)

array([40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10,  7,  4])

In [2]:
import numpy as np
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
import random

In [5]:
%timeit rolls_list  = \
    [random.randrange(1,7) for i in range(0,6000000)]


3.63 s ± 69.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit rolls_array = np.random.randint(1,7,6000000)


46.6 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

460 ms ± 16.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

5.3 s ± 247 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

45.7 ms ± 1.44 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [12]:
## 7.6 sc
%timeit sum([x for x in range(10_000_000)])

638 ms ± 25.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
 %timeit np.arange(10_000_000).sum()

13 ms ± 584 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
## 7.8
grades = np.array([[87, 96, 70], [100, 87, 90],
                    [94, 77, 90], [100, 81, 82]])

In [16]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [19]:
grades.max()

100

In [20]:
grades.mean()

87.83333333333333

In [21]:
grades.std()

8.792357792739987

In [18]:
grades.min()

70

In [22]:
 grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [23]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [24]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)

In [26]:
grades

array([[87, 75, 64, 92],
       [62, 71, 74, 87],
       [78, 62, 92, 67]])

In [27]:
grades.mean()

75.91666666666667

In [28]:
grades.mean(axis=0)

array([75.66666667, 69.33333333, 76.66666667, 82.        ])

In [29]:
grades.mean(axis=1)

array([79.5 , 73.5 , 74.75])

In [32]:
### 7.9
numbers = np.array([1, 4, 9, 16, 25, 36])

In [35]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [38]:
n2 = np.arange(1,7) ** 10

In [39]:
n2

array([       1,     1024,    59049,  1048576,  9765625, 60466176],
      dtype=int32)

In [41]:
### 7.10

n2.view()

array([       1,     1024,    59049,  1048576,  9765625, 60466176],
      dtype=int32)

In [42]:
n2v = n2.view()

In [43]:
n2v

array([       1,     1024,    59049,  1048576,  9765625, 60466176],
      dtype=int32)